### ISSUE TITLE
sbt test fails on second launch

### ISSUE THREAD

**Issue by elppc** [filodb/FiloDB#107]
SaveAsFiloTest fails on the second "sbt test" launch. Also tried to delete "unittest" and "unittest2" keyspaces in cassandra related to the tests.
To reproduce:

```
git clone https://github.com/tuplejump/FiloDB.git
cd FiloDB/
sbt test
```

==> all tests passed
remove unittest and unittest2 with cqlsh
`
sbt test
`
==> 9 tests failed in SaveAsFiloTest

```
SaveAsFiloTest:
[info] - should create missing columns and partitions and write table
[info] - should throw ColumnTypeMismatch if existing columns are not same type
[info] - should throw BadSchemaError if illegal computed column specification or bad schema
[info] - should not delete original metadata if overwrite with bad schema definition *** FAILED ***
[info]   Dataset(gdelt1,List(Projection(0,gdelt1,List(id),:string 0,false,List())),List(:string part0),{"chunkSize":5000}) did not equal Dataset(gdelt1,List(Projection(0,unittest.gdelt1,List(id),:string 0,false,List())),List(:string part0),{"chunkSize":5000}) (SaveAsFiloTest.scala:124)
[info] - should write table if there are existing matching columns
[info] - should throw error in ErrorIfExists mode if dataset already exists
[info] - should write and read using DF write() and read() APIs
[info] - should write and read to another keyspace using DF write() and read() APIs *** FAILED ***
[info]   Expected exception filodb.core.NotFoundError to be thrown, but no exception was thrown. (SaveAsFiloTest.scala:178)
[info] - should overwrite existing data if mode=Overwrite *** FAILED ***        
[info]   12092 did not equal 4032 (SaveAsFiloTest.scala:208)
[info] - should append data in Append mode *** FAILED ***
[info]   12092 did not equal 8062 (SaveAsFiloTest.scala:240)
[2016-06-21 22:38:24,161] ERROR a.actor.OneForOneStrategy [akka://filo-spark/user/coordinator/ds-coord-gdelt2-0] - java.lang.String cannot be cast to java.lang.Long
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
    at scala.runtime.BoxesRunTime.unboxToLong(BoxesRunTime.java:110) ~[scala-library-2.10.4.jar:na]
    at org.apache.spark.sql.Row$class.getLong(Row.scala:224) ~[spark-catalyst_2.10-1.5.1.jar:1.5.1]
    at org.apache.spark.sql.catalyst.expressions.GenericRow.getLong(rows.scala:191) ~[spark-catalyst_2.10-1.5.1.jar:1.5.1]
    at filodb.spark.RddRowReader.getLong(RddRowSourceActor.scala:74) ~[classes/:na]
    at org.velvia.filo.RowReader$LongFieldExtractor$.getField(RowReader.scala:102) ~[filo-scala_2.10-0.2.4.jar:0.2.4]
    at org.velvia.filo.RowReader$LongFieldExtractor$.getField(RowReader.scala:101) ~[filo-scala_2.10-0.2.4.jar:0.2.4]
    at org.velvia.filo.VectorBuilderBase$class.add(VectorBuilder.scala:35) ~[filo-scala_2.10-0.2.4.jar:0.2.4]
    at org.velvia.filo.VectorBuilder.add(VectorBuilder.scala:65) ~[filo-scala_2.10-0.2.4.jar:0.2.4]
    at org.velvia.filo.RowToVectorBuilder.addRow(RowToVectorBuilder.scala:69) ~[filo-scala_2.10-0.2.4.jar:0.2.4]
    at filodb.core.reprojector.FiloAppendStore$$anonfun$appendRows$1.apply(FiloAppendStore.scala:61) ~[classes/:na]
    at filodb.core.reprojector.FiloAppendStore$$anonfun$appendRows$1.apply(FiloAppendStore.scala:61) ~[classes/:na]
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) ~[scala-library-2.10.4.jar:na]
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47) ~[scala-library-2.10.4.jar:na]
    at filodb.core.reprojector.FiloAppendStore.appendRows(FiloAppendStore.scala:61) ~[classes/:na]
    at filodb.core.reprojector.FiloMemTable.ingestRows(FiloMemTable.scala:74) ~[classes/:na]
    at filodb.coordinator.DatasetCoordinatorActor.filodb$coordinator$DatasetCoordinatorActor$$writeToMemTable(DatasetCoordinatorActor.scala:183) ~[classes/:na]
    at filodb.coordinator.DatasetCoordinatorActor$$anonfun$receive$1.applyOrElse(DatasetCoordinatorActor.scala:295) ~[classes/:na]
    at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.10-2.3.15.jar:na]
    at filodb.coordinator.BaseActor.aroundReceive(BaseActor.scala:6) ~[classes/:na]
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.10-2.3.15.jar:na]
    at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.10-2.3.15.jar:na]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.10-2.3.15.jar:na]
    at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.10-2.3.15.jar:na]
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.10-2.3.15.jar:na]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.10.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.10.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.10.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.10.4.jar:na]
[2016-06-21 22:38:28,145] ERROR o.a.s.executor.Executor [] - Exception in task 0.0 in stage 33.0 (TID 36)
scala.MatchError: IngestionErr(Ingestion actors shut down, check error logs) (of class filodb.coordinator.RowSource$IngestionErr)
    at filodb.spark.package$.ingestRddRows(package.scala:94) ~[classes/:na]
    at filodb.spark.FiloContext$$anonfun$insertIntoFilo$extension$1.apply(FiloContext.scala:159) ~[classes/:na]
    at filodb.spark.FiloContext$$anonfun$insertIntoFilo$extension$1.apply(FiloContext.scala:155) ~[classes/:na]
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$18.apply(RDD.scala:723) ~[spark-core_2.10-1.5.1.jar:1.5.1]
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$18.apply(RDD.scala:723) ~[spark-core_2.10-1.5.1.jar:1.5.1]
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38) ~[spark-core_2.10-1.5.1.jar:1.5.1]
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297) ~[spark-core_2.10-1.5.1.jar:1.5.1]
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:264) ~[spark-core_2.10-1.5.1.jar:1.5.1]
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66) ~[spark-core_2.10-1.5.1.jar:1.5.1]
    at org.apache.spark.scheduler.Task.run(Task.scala:88) ~[spark-core_2.10-1.5.1.jar:1.5.1]
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214) ~[spark-core_2.10-1.5.1.jar:1.5.1]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
[2016-06-21 22:38:28,164] WARN  o.a.s.s.TaskSetManager [] - Lost task 0.0 in stage 33.0 (TID 36, localhost): scala.MatchError: IngestionErr(Ingestion actors shut down, check error logs) (of class filodb.coordinator.RowSource$IngestionErr)
    at filodb.spark.package$.ingestRddRows(package.scala:94)
    at filodb.spark.FiloContext$$anonfun$insertIntoFilo$extension$1.apply(FiloContext.scala:159)
    at filodb.spark.FiloContext$$anonfun$insertIntoFilo$extension$1.apply(FiloContext.scala:155)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$18.apply(RDD.scala:723)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$18.apply(RDD.scala:723)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:88)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

[2016-06-21 22:38:28,175] ERROR o.a.s.s.TaskSetManager [] - Task 0 in stage 33.0 failed 1 times; aborting job
[info] - should append data using SQL INSERT INTO statements *** FAILED ***
[info]   org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 33.0 failed 1 times, most recent failure: Lost task 0.0 in stage 33.0 (TID 36, localhost): scala.MatchError: IngestionErr(Ingestion actors shut down, check error logs) (of class filodb.coordinator.RowSource$IngestionErr)
[info]  at filodb.spark.package$.ingestRddRows(package.scala:94)
[info]  at filodb.spark.FiloContext$$anonfun$insertIntoFilo$extension$1.apply(FiloContext.scala:159)
[info]  at filodb.spark.FiloContext$$anonfun$insertIntoFilo$extension$1.apply(FiloContext.scala:155)
[info]  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$18.apply(RDD.scala:723)
[info]  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$18.apply(RDD.scala:723)
[info]  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
[info]  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297)
[info]  at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
[info]  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
[info]  at org.apache.spark.scheduler.Task.run(Task.scala:88)
[info]  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
[info]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]  at java.lang.Thread.run(Thread.java:745)
[info] 
[info] Driver stacktrace:
[info]   at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1283)
[info]   at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1271)
[info]   at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1270)
[info]   at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[info]   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
[info]   at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1270)
[info]   at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:697)
[info]   at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:697)
[info]   at scala.Option.foreach(Option.scala:236)
[info]   at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:697)
[info]   ...
[info]   Cause: scala.MatchError: IngestionErr(Ingestion actors shut down, check error logs) (of class filodb.coordinator.RowSource$IngestionErr)
[info]   at filodb.spark.package$.ingestRddRows(package.scala:94)
[info]   at filodb.spark.FiloContext$$anonfun$insertIntoFilo$extension$1.apply(FiloContext.scala:159)
[info]   at filodb.spark.FiloContext$$anonfun$insertIntoFilo$extension$1.apply(FiloContext.scala:155)
[info]   at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$18.apply(RDD.scala:723)
[info]   at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$18.apply(RDD.scala:723)
[info]   at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
[info]   at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297)
[info]   at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
[info]   at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
[info]   at org.apache.spark.scheduler.Task.run(Task.scala:88)
[info]   ...
[info] - should be able to write with a user-specified partitioning column *** FAILED ***
[info]   6 did not equal 3 (SaveAsFiloTest.scala:265)
[info] - should be able to write with multi-column partition keys               
[info] - should be able to parse and use partition filters in queries           
[info] - should be able to parse and use partition filters even if partition has computed column
[info] - should be able to write with multi-column row keys and filter by segment key *** FAILED ***
[info]   1406 did not equal 492 (SaveAsFiloTest.scala:335)
[info] - should be able to write with multi-column row keys and filter by segment key equals *** FAILED ***
[info]   1406 did not equal 492 (SaveAsFiloTest.scala:353)
[2016-06-21 22:39:01,127] ERROR a.actor.OneForOneStrategy [akka://filo-spark/user/coordinator/ds-coord-test1-0] - Null partition value for col index 0
filodb.core.NullKeyValue: Null partition value for col index 0
    at filodb.core.SingleKeyTypeBase$$anonfun$getKeyFunc$1.apply(KeyType.scala:62) ~[classes/:na]
    at filodb.core.SingleKeyTypeBase$$anonfun$getKeyFunc$1.apply(KeyType.scala:58) ~[classes/:na]
    at filodb.core.store.AppendingChunkMergingStrategy$$anonfun$1.apply(ChunkMergingStrategy.scala:109) ~[classes/:na]
    at filodb.core.store.AppendingChunkMergingStrategy$$anonfun$1.apply(ChunkMergingStrategy.scala:108) ~[classes/:na]
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:328) ~[scala-library-2.10.4.jar:na]
    at scala.collection.Iterator$class.toStream(Iterator.scala:1143) ~[scala-library-2.10.4.jar:na]
    at scala.collection.AbstractIterator.toStream(Iterator.scala:1157) ~[scala-library-2.10.4.jar:na]
    at scala.collection.TraversableOnce$class.toSeq(TraversableOnce.scala:261) ~[scala-library-2.10.4.jar:na]
    at scala.collection.AbstractIterator.toSeq(Iterator.scala:1157) ~[scala-library-2.10.4.jar:na]
    at filodb.core.store.AppendingChunkMergingStrategy.mergeSegments(ChunkMergingStrategy.scala:112) ~[classes/:na]
    at filodb.core.store.CachedMergingColumnStore$$anonfun$appendSegment$1.apply(ColumnStore.scala:216) ~[classes/:na]
    at filodb.core.store.CachedMergingColumnStore$$anonfun$appendSegment$1.apply(ColumnStore.scala:215) ~[classes/:na]
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:206) ~[scala-library-2.10.4.jar:na]
    at scala.util.Try$.apply(Try.scala:161) ~[scala-library-2.10.4.jar:na]
    at scala.util.Success.map(Try.scala:206) ~[scala-library-2.10.4.jar:na]
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[scala-library-2.10.4.jar:na]
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[scala-library-2.10.4.jar:na]
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) ~[scala-library-2.10.4.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_91]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_91]
[info] - should be able to ingest Spark Timestamp columns and query them *** FAILED ***
[info]   null did not equal 1.1 (SaveAsFiloTest.scala:370)

```

**Comment by velvia** [comment]
Thanks.  Did the InMemoryTest run before SaveAsFiloTest?   That is the likely culprit.   I’ll try fixing this; in the meantime, if you do “testOnly filodb.spark.SaveAsFiloTest” it should pass.

**Comment by velvia** [comment]
Found a fix for this, though it took a long time.  There is a way to get SBT to launch each test in its own JVM, and that allows restarting Spark with different settings.

**Comment by velvia** [comment]
This is now fixed in the new-storage-format branch.
