### ISSUE TITLE
Spark multi-node setup row not found

### ISSUE THREAD

**Issue by eric41** [filodb/FiloDB#118]
Hi,

In my setup I tried using FiloDB with a single Spark Worker (+ Master) and single Cassandra instance and this all worked perfectly fine. Then I tried adding a second machine with a Spark Worker and Cassandra instance, but this broke down with the StringIndexOutOfBoundsException posted at the end of this post.

The exception suggests that Spark cannot find the row it's looking for in FiloDB/Cassandra, so I tried to use two Spark Workers with a single Cassandra instance, but this unfortunately also failed with a similar exception (the RowNo was different). When I browsed through some other issues in this repository, it was noted you should sort the data before ingestion. However, this did not solve the issue, neither did repartitioning the data to 2 partitions. Is there anything else I should take into account?

Currently my data is too big to post here on github, so I'll try to reduce it to a simple example in which it fails.

Regards,
Eric

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 942943960
        at java.lang.String.checkBounds(String.java:385)
        at java.lang.String.<init>(String.java:462)
        at com.google.flatbuffers.Table.__string(Table.java:50)
        at org.velvia.filo.vector.SimpleStringVector.data(SimpleStringVector.java:18)
        at org.velvia.filo.codecs.SimpleStringWrapper.apply(SimpleWrappers.scala:46)
        at org.velvia.filo.codecs.SimpleStringWrapper.apply(SimpleWrappers.scala:40)
        at filodb.spark.SparkRowReader.getUTF8String(FiloRelation.scala:388)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(generated.java:61)
        at org.apache.spark.sql.execution.Project$$anonfun$1$$anonfun$apply$1.apply(basicOperators.scala:51)
        at org.apache.spark.sql.execution.Project$$anonfun$1$$anonfun$apply$1.apply(basicOperators.scala:49)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at org.apache.spark.sql.execution.aggregate.TungstenAggregationIterator.processInputs(TungstenAggregationIterator.scala:512)
        at org.apache.spark.sql.execution.aggregate.TungstenAggregationIterator.<init>(TungstenAggregationIterator.scala:686)
        at org.apache.spark.sql.execution.aggregate.TungstenAggregate$$anonfun$doExecute$1$$anonfun$2.apply(TungstenAggregate.scala:95)
        at org.apache.spark.sql.execution.aggregate.TungstenAggregate$$anonfun$doExecute$1$$anonfun$2.apply(TungstenAggregate.scala:86)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by velvia** [comment]
Hi Eric,

currently with multiple workers you need to ensure your data is sorted such that records with the same partition key end up in the same node or worker.   Future versions will fix this.   The easiest way to accomplish this right now is to sort your data in Spark first.

**Comment by velvia** [comment]
@eric41 feel free to reopen this when you are able to verify, thanks!  Also, a feature to automatically sort the data before ingestion is coming which will help with all of this.

**Comment by elppc** [comment]
Hi
I have a similar error. Can you detail more about this sort requirement ? 
- Spark is not aware of the node hosting the partition so how could you be sure if you have more than one partition per node ? Should I match the number of partitions with the number of workers ?
- The sort function in dataframe/dataset doesn't control the partitioning, should I use repartition ?
- If I am using a computed column in the partition key, should I reimplement it in UDF to provide a Column type to repartition function?

**Comment by velvia** [comment]
Sorry, what I mean by partition are FiloDB partitions.

Basically, the Spark partitions doesn’t matter.  What matters is that you sort the data frame by the partition key, such that data/records going towards or containing the same FiloDB partition key ends up on the same physical Spark executor.

The sorting implementation will soon be pushed into the open source tree, in a branch however.   Probably by the end of December.
