### ISSUE TITLE
Support for UTF8 String predicate pushdown to data source level

### ISSUE THREAD

**Issue by parekuti** [filodb/FiloDB#134]
Unable to fetch data using key filter with UTF8String type. Here is the error from the logs.

[2016-12-30 10:54:23,402] INFO  filodb.spark.FiloRelation$ - Pushing down partition column cli_no, filters List(EqualTo(cli_no,0238))
[2016-12-30 10:54:23,402] INFO  filodb.spark.FiloRelation$ - Incoming Segment Filters [List(EqualTo(arm_savings_ctgy_cd,A01))]
[2016-12-30 10:54:23,406] ERROR o.a.s.s.h.t.SparkExecuteStatementOperation - Error executing query:
java.lang.ClassCastException: org.apache.spark.sql.types.UTF8String cannot be cast to java.lang.String
        at filodb.core.query.SingleValueRowReader.getString(KeyFilter.scala:114) ~[filodb-spark-assembly.jar:0.2.0.23-dse-4.8-spark-1.4]
        at org.velvia.filo.RowReader$StringFieldExtractor$.getField(RowReader.scala:118) ~[filodb-spark-assembly.jar:0.2.0.23-dse-4.8-spark-1.4]
        at org.velvia.filo.RowReader$StringFieldExtractor$.getField(RowReader.scala:117) ~[filodb-spark-assembly.jar:0.2.0.23-dse-4.8-spark-1.4]
        at filodb.core.SingleKeyTypeBase$$anonfun$getKeyFunc$1.apply(KeyType.scala:60) ~[filodb-spark-assembly.jar:0.2.0.23-dse-4.8-spark-1.4]
        at filodb.core.SingleKeyTypeBase$$anonfun$getKeyFunc$1.apply(KeyType.scala:58) ~[filodb-spark-assembly.jar:0.2.0.23-dse-4.8-spark-1.4]
        at filodb.core.query.KeyFilter$.parseSingleValue(KeyFilter.scala:36) ~[filodb-spark-assembly.jar:0.2.0.23-dse-4.8-spark-1.4]
        at filodb.spark.FiloRelation$.segmentRangeScan(FiloRelation.scala:124) ~[filodb-spark-assembly.jar:0.2.0.23-dse-4.8-spark-1.4]
        at filodb.spark.FiloRelation.scanByPartitions(FiloRelation.scala:261) ~[filodb-spark-assembly.jar:0.2.0.23-dse-4.8-spark-1.4]
        at filodb.spark.FiloRelation.buildScan(FiloRelation.scala:318) ~[filodb-spark-assembly.jar:0.2.0.23-dse-4.8-spark-1.4]
        at org.apache.spark.sql.sources.DataSourceStrategy$$anonfun$3.apply(DataSourceStrategy.scala:50) ~[spark-sql_2.10-1.4.2.6.jar:1.4.2.6]
        at org.apache.spark.sql.sources.DataSourceStrategy$$anonfun$3.apply(DataSourceStrategy.scala:50) ~[spark-sql_2.10-1.4.2.6.jar:1.4.2.6]
        at org.apache.spark.sql.sources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:266) ~[spark-sql_2.10-1.4.2.6.jar:1.4.2.6]
        at org.apache.spark.sql.sources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:265) ~[spark-sql_2.10-1.4.2.6.jar:1.4.2.6]
        at org.apache.spark.sql.sources.DataSourceStrategy$.pruneFilterProjectRaw(DataSourceStrategy.scala:302) ~[spark-sql_2.10-1.4.2.6.jar:1.4.2.6]
        at org.apache.spark.sql.sources.DataSourceStrategy$.pruneFilterProject(DataSourceStrategy.scala:261) ~[spark-sql_2.10-1.4.2.6.jar:1.4.2.6]
        at org.apache.spark.sql.sources.DataSourceStrategy$.apply(DataSourceStrategy.scala:46) ~[spark-sql_2.10-1.4.2.6.jar:1.4.2.6]
        at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58) ~[spark-catalyst_2.10-1.4.2.6.jar:1.4.2.6]
        at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58) ~[spark-catalyst_2.10-1.4.2.6.jar:1.4.2.6]
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371) ~[scala-library-2.10.5.jar:na]
        at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:59) ~[spark-catalyst_2.10-1.4.2.6.jar:1.4.2.6]
        at org.apache.spark.sql.SQLContext$QueryExecution.sparkPlan$lzycompute(SQLContext.scala:943) ~[spark-sql_2.10-1.4.2.6.jar:1.4.2.6]
        at org.apache.spark.sql.SQLContext$QueryExecution.sparkPlan(SQLContext.scala:941) ~[spark-sql_2.10-1.4.2.6.jar:1.4.2.6]
        at org.apache.spark.sql.SQLContext$QueryExecution.executedPlan$lzycompute(SQLContext.scala:947) ~[spark-sql_2.10-1.4.2.6.jar:1.4.2.6]
        at org.apache.spark.sql.SQLContext$QueryExecution.executedPlan(SQLContext.scala:947) ~[spark-sql_2.10-1.4.2.6.jar:1.4.2.6]
        at org.apache.spark.sql.DataFrame.collect(DataFrame.scala:1269) ~[spark-sql_2.10-1.4.2.6.jar:1.4.2.6]
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.run(Shim13.scala:193) ~[spark-hive-thriftserver_2.10-1.4.2.6.jar:1.4.2.6]
        at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatementInternal(HiveSessionImpl.java:231) [hive-service-0.13.1a.jar:0.13.1a]
        at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatementAsync(HiveSessionImpl.java:218) [hive-service-0.13.1a.jar:0.13.1a]
        at org.apache.hive.service.cli.CLIService.executeStatementAsync(CLIService.java:233) [hive-service-0.13.1a.jar:0.13.1a]
        at org.apache.hive.service.cli.thrift.ThriftCLIService.ExecuteStatement(ThriftCLIService.java:344) [hive-service-0.13.1a.jar:0.13.1a]
        at org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1313) [hive-service-0.13.1a.jar:0.13.1a]
        at org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1298) [hive-service-0.13.1a.jar:0.13.1a]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39) [libthrift-0.9.3.jar:0.9.3]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) [libthrift-0.9.3.jar:0.9.3]
        at org.apache.hive.service.auth.TSetIpAddressProcessor.process(TSetIpAddressProcessor.java:55) [hive-service-0.13.1a.jar:4.8.10]
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286) [libthrift-0.9.3.jar:0.9.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_77]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_77]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]

**Comment by velvia** [comment]
Closing as FiloDB has pivoted to an in-memory time series DB and this code path is not applicable any more.
