### ISSUE TITLE
FiloDB Write format filodb.spark giving errors

### ISSUE THREAD

**Issue by PallaviPersistent** [filodb/FiloDB#150]
**Branch, version, commit** 

**OS and Environment**Red Hat Enterprise Linux Server release 7.2

**JVM version**java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

**Scala version**
Scala version 2.11.8
**Kafka and Cassandra versions and setup**

**Spark version if used**
Spark version 2.0.0
**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
Spark Standalone
**Actual (wrong) behavior**
scala> test.write.format("filodb.spark").option("path","/root/FiloDB/JSON").option("dataset","jsontest").option("row_keys","action").option("partition_keys","timestamp").mode(SaveMode.Overwrite).save()
java.util.NoSuchElementException: key not found: ArrayType(StringType,true)
  at scala.collection.MapLike$class.default(MapLike.scala:228)
  at scala.collection.AbstractMap.default(Map.scala:59)
  at scala.collection.MapLike$class.apply(MapLike.scala:141)
  at scala.collection.AbstractMap.apply(Map.scala:59)
  at filodb.spark.package$$anonfun$dfToFiloColumns$1.apply(package.scala:132)
  at filodb.spark.package$$anonfun$dfToFiloColumns$1.apply(package.scala:131)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at org.apache.spark.sql.types.StructType.foreach(StructType.scala:95)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at org.apache.spark.sql.types.StructType.map(StructType.scala:95)
  at filodb.spark.package$.dfToFiloColumns(package.scala:131)
  at filodb.spark.FiloContext$.createOrUpdateDataset$extension(FiloContext.scala:57)
  at filodb.spark.FiloContext$.saveAsFilo$extension(FiloContext.scala:117)
  at filodb.spark.DefaultSource.createRelation(DefaultSource.scala:63)
  at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:429)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:211)
  ... 50 elided

**Steps to reproduce**
scala> val events = sc.parallelize(
     | """{"action":["create","drop"],"timestamp":1452121277}""" ::
     | """{"action":["create","drop"],"timestamp":"1452121277"}""" ::
     | """{"action":["create","drop"],"timestamp":""}""" ::
     | """{"action":["create","drop"],"timestamp":null}""" ::
     | """{"action":["create","drop"],"timestamp":"null"}""" ::
     | Nil
     | )
events: org.apache.spark.rdd.RDD[String] = ParallelCollectionRDD[27] at parallelize at <console>:28

scala> val test= sqlContext.read.json(events)
test: org.apache.spark.sql.DataFrame = [action: array<string>, timestamp: string]

scala> test.write.format("filodb.spark").option("path","/root/FiloDB/JSON").option("dataset","jsontest").option("row_keys","action").option("partition_keys","timestamp").mode(SaveMode.Overwrite).save()

**Logs**

```
some log
```

or as attached file (see below)

Unused parts of this template should be removed (including this line).

**Comment by velvia** [comment]
Sorry, for now we don't support Array types or nested lists in the Spark schema.   You need to flatten the data.   Something like `test.withColumn("firstAction", .....).select(....)` and leave out the nested list when you select.  Or maybe turn each JSON into two rows?

**Comment by velvia** [comment]
Closing as FiloDB has pivoted to an in-memory time series DB and this code path is not applicable any more.
